Import Library yang diperlukan

In [2]:
import numpy as np
import pickle as pkl
import matplotlib.pyplot as plt
import pandas as pd

Read File CSV

In [3]:
df = pd.read_csv('Dataset_A_loan.csv')
df

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,male,Associate,47971.0,6,RENT,15000.0,MEDICAL,15.66,0.31,3.0,645,No,1
44996,37.0,female,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44997,33.0,male,Associate,56942.0,7,RENT,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,No,1
44998,29.0,male,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1
44999,24.0,male,High School,51609.0,1,RENT,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,No,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      45000 non-null  float64
 1   person_gender                   45000 non-null  object
 2   person_education                45000 non-null  object
 3   person_income                   42750 non-null  float64
 4   person_emp_exp                  45000 non-null  int64
 5   person_home_ownership           45000 non-null  object
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  object
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  int64
 12  previous_loan_defaults_on_file  45000 non-null  object
 13  loan_status                     45000 non-null  int64
dtypes: float64(6), int64(3), object(5)
memory usage: 4.8+ MB

In [5]:
df['person_education'].value_counts()

person_education
Bachelor       13399
Associate      12028
High School    11972
Master          6980
Doctorate        621
Name: count, dtype: int64

In [6]:
df['person_home_ownership'].value_counts()

person_home_ownership
RENT        23443
MORTGAGE    18489
OWN          2951
OTHER         117
Name: count, dtype: int64

In [7]:
df['loan_intent'].value_counts()

loan_intent
EDUCATION            9153
MEDICAL              8548
VENTURE              7819
PERSONAL             7552
DEBTCONSOLIDATION    7145
HOMEIMPROVEMENT      4783
Name: count, dtype: int64

In [8]:
df['previous_loan_defaults_on_file'].value_counts()

previous_loan_defaults_on_file
Yes    22858
No     22142
Name: count, dtype: int64

In [9]:
df['person_gender'].value_counts()

person_gender
male       24799
female     20111
Male          45
fe male       45
Name: count, dtype: int64

Split Data into Train and Test Data

In [10]:
idf=df.drop(['loan_status'],axis=1)
odf=df['loan_status']

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(idf, odf, test_size = 0.2, random_state = 42)

In [12]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 36000 entries, 25180 to 15795
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      36000 non-null  float64
 1   person_gender                   36000 non-null  object
 2   person_education                36000 non-null  object
 3   person_income                   34231 non-null  float64
 4   person_emp_exp                  36000 non-null  int64
 5   person_home_ownership           36000 non-null  object
 6   loan_amnt                       36000 non-null  float64
 7   loan_intent                     36000 non-null  object
 8   loan_int_rate                   36000 non-null  float64
 9   loan_percent_income             36000 non-null  float64
 10  cb_person_cred_hist_length      36000 non-null  float64
 11  credit_score                    36000 non-null  int64
 12  previous_loan_defaults_on_file  36000 non-null  object
dtypes: float64(6), int64(2), object(5)
memory usage: 3.8+ MB

In [13]:
x_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9000 entries, 37979 to 5321
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      9000 non-null   float64
 1   person_gender                   9000 non-null   object
 2   person_education                9000 non-null   object
 3   person_income                   8519 non-null   float64
 4   person_emp_exp                  9000 non-null   int64
 5   person_home_ownership           9000 non-null   object
 6   loan_amnt                       9000 non-null   float64
 7   loan_intent                     9000 non-null   object
 8   loan_int_rate                   9000 non-null   float64
 9   loan_percent_income             9000 non-null   float64
 10  cb_person_cred_hist_length      9000 non-null   float64
 11  credit_score                    9000 non-null   int64
 12  previous_loan_defaults_on_file  9000 non-null   object
dtypes: float64(6), int64(2), object(5)
memory usage: 984.4+ KB

Handle Missing Values

Diasumsikan person_income yang bernilai NULL merupakan nilai 0 alias orang tersebut belum memiliki income sesuai dengan data saat ini

In [14]:
x_train['person_income'].fillna(0, inplace=True)
x_test['person_income'].fillna(0, inplace=True)

C:\Users\hartono\AppData\Local\Temp\ipykernel_23536\81170671.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  x_train['person_income'].fillna(0, inplace=True)
C:\Users\hartono\AppData\Local\Temp\ipykernel_23536\81170671.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  x_test['person_income'].fillna(0, inplace=True)

In [15]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 36000 entries, 25180 to 15795
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      36000 non-null  float64
 1   person_gender                   36000 non-null  object
 2   person_education                36000 non-null  object
 3   person_income                   36000 non-null  float64
 4   person_emp_exp                  36000 non-null  int64
 5   person_home_ownership           36000 non-null  object
 6   loan_amnt                       36000 non-null  float64
 7   loan_intent                     36000 non-null  object
 8   loan_int_rate                   36000 non-null  float64
 9   loan_percent_income             36000 non-null  float64
 10  cb_person_cred_hist_length      36000 non-null  float64
 11  credit_score                    36000 non-null  int64
 12  previous_loan_defaults_on_file  36000 non-null  object
dtypes: float64(6), int64(2), object(5)
memory usage: 3.8+ MB

In [16]:
x_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9000 entries, 37979 to 5321
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      9000 non-null   float64
 1   person_gender                   9000 non-null   object
 2   person_education                9000 non-null   object
 3   person_income                   9000 non-null   float64
 4   person_emp_exp                  9000 non-null   int64
 5   person_home_ownership           9000 non-null   object
 6   loan_amnt                       9000 non-null   float64
 7   loan_intent                     9000 non-null   object
 8   loan_int_rate                   9000 non-null   float64
 9   loan_percent_income             9000 non-null   float64
 10  cb_person_cred_hist_length      9000 non-null   float64
 11  credit_score                    9000 non-null   int64
 12  previous_loan_defaults_on_file  9000 non-null   object
dtypes: float64(6), int64(2), object(5)
memory usage: 984.4+ KB

Fix person_gender non standard value

In [17]:
x_train['person_gender'].value_counts()

person_gender
male       19782
female     16149
Male          35
fe male       34
Name: count, dtype: int64

In [18]:
x_test['person_gender'].value_counts()

person_gender
male       5017
female     3962
fe male      11
Male         10
Name: count, dtype: int64

In [19]:
x_train['person_gender'].replace('fe male',"female", inplace=True)
x_train['person_gender'].replace('Male',"male", inplace=True)

x_test['person_gender'].replace('fe male',"female", inplace=True)
x_test['person_gender'].replace('Male',"male", inplace=True)

C:\Users\hartono\AppData\Local\Temp\ipykernel_23536\1476506354.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  x_train['person_gender'].replace('fe male',"female", inplace=True)
C:\Users\hartono\AppData\Local\Temp\ipykernel_23536\1476506354.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  x_train['person_gender'].replace('Male',"male", inplace=True)
C:\Users\hartono\AppData\Local\Temp\ipykernel_23536\1476506354.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  x_test['person_gender'].replace('fe male',"female", inplace=True)
C:\Users\hartono\AppData\Local\Temp\ipykernel_23536\1476506354.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  x_test['person_gender'].replace('Male',"male", inplace=True)

In [20]:
x_train['person_gender'].value_counts()

person_gender
male      19817
female    16183
Name: count, dtype: int64

In [21]:
x_test['person_gender'].value_counts()

person_gender
male      5027
female    3973
Name: count, dtype: int64

Encoding Categorical Variable

In [22]:
df['person_education'].value_counts()

person_education
Bachelor       13399
Associate      12028
High School    11972
Master          6980
Doctorate        621
Name: count, dtype: int64

In [23]:
df['person_home_ownership'].value_counts()

person_home_ownership
RENT        23443
MORTGAGE    18489
OWN          2951
OTHER         117
Name: count, dtype: int64

In [24]:
df['loan_intent'].value_counts()

loan_intent
EDUCATION            9153
MEDICAL              8548
VENTURE              7819
PERSONAL             7552
DEBTCONSOLIDATION    7145
HOMEIMPROVEMENT      4783
Name: count, dtype: int64

In [25]:
df['previous_loan_defaults_on_file'].value_counts()

previous_loan_defaults_on_file
Yes    22858
No     22142
Name: count, dtype: int64

In [26]:
df['person_gender'].value_counts()

person_gender
male       24799
female     20111
Male          45
fe male       45
Name: count, dtype: int64

In [27]:
encode_gender={"person_gender": {"male":1,"female" :0}}
x_train=x_train.replace(encode_gender)
x_test=x_test.replace(encode_gender)

C:\Users\hartono\AppData\Local\Temp\ipykernel_23536\3499946962.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  x_train=x_train.replace(encode_gender)
C:\Users\hartono\AppData\Local\Temp\ipykernel_23536\3499946962.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  x_test=x_test.replace(encode_gender)

In [28]:
encode_pl={"previous_loan_defaults_on_file": {"Yes":1,"No" :0}}
x_train=x_train.replace(encode_pl)
x_test=x_test.replace(encode_pl)

C:\Users\hartono\AppData\Local\Temp\ipykernel_23536\203770116.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  x_train=x_train.replace(encode_pl)
C:\Users\hartono\AppData\Local\Temp\ipykernel_23536\203770116.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  x_test=x_test.replace(encode_pl)

In [29]:
x_train.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file
25180,34.0,0,Bachelor,97265.0,11,MORTGAGE,15000.0,PERSONAL,12.73,0.15,9.0,631,0
12555,25.0,1,High School,0.0,3,RENT,12000.0,VENTURE,11.86,0.16,4.0,659,1
29153,41.0,0,Master,322597.0,18,MORTGAGE,24000.0,PERSONAL,10.37,0.07,11.0,683,1
23838,27.0,1,Associate,94232.0,4,RENT,9600.0,EDUCATION,17.14,0.10,7.0,641,0
35686,27.0,1,Master,0.0,7,RENT,7059.0,HOMEIMPROVEMENT,12.97,0.08,3.0,706,1

In [30]:
x_test.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file
37979,32.0,1,Associate,96865.0,10,MORTGAGE,7500.0,EDUCATION,6.04,0.08,10.0,601,0
9911,24.0,1,Associate,56838.0,6,RENT,9000.0,EDUCATION,11.49,0.16,4.0,647,1
43386,22.0,0,Master,37298.0,0,RENT,5000.0,MEDICAL,14.88,0.13,4.0,711,0
13822,23.0,0,Bachelor,39944.0,1,OWN,5000.0,VENTURE,13.99,0.13,3.0,597,1
44810,42.0,1,High School,67974.0,20,MORTGAGE,10000.0,HOMEIMPROVEMENT,15.41,0.15,11.0,586,0

In [31]:
fn = 'encode_gender.pkl'
pkl.dump(encode_gender, open(fn, 'wb'))

In [32]:
fn = 'encode_pl.pkl'
pkl.dump(encode_pl, open(fn, 'wb'))

In [33]:
from sklearn.preprocessing import OneHotEncoder

pe_train_enc=x_train[['person_education']]
ph_train_enc=x_train[['person_home_ownership']]
li_train_enc=x_train[['loan_intent']]


pe_test_enc=x_test[['person_education']]
ph_test_enc=x_test[['person_home_ownership']]
li_test_enc=x_test[['loan_intent']]

pe_enc=OneHotEncoder()
ph_enc=OneHotEncoder()
li_enc=OneHotEncoder()

pe_train_enc=pd.DataFrame(pe_enc.fit_transform(pe_train_enc).toarray(),columns=pe_enc.get_feature_names_out())
ph_train_enc=pd.DataFrame(ph_enc.fit_transform(ph_train_enc).toarray(),columns=ph_enc.get_feature_names_out())
li_train_enc=pd.DataFrame(li_enc.fit_transform(li_train_enc).toarray(),columns=li_enc.get_feature_names_out())

pe_test_enc=pd.DataFrame(pe_enc.fit_transform(pe_test_enc).toarray(),columns=pe_enc.get_feature_names_out())
ph_test_enc=pd.DataFrame(ph_enc.fit_transform(ph_test_enc).toarray(),columns=ph_enc.get_feature_names_out())
li_test_enc=pd.DataFrame(li_enc.fit_transform(li_test_enc).toarray(),columns=li_enc.get_feature_names_out())

x_train=x_train.reset_index()
x_test=x_test.reset_index()

x_train_enc=pd.concat([x_train,pe_train_enc,ph_train_enc,li_train_enc], axis=1)
x_test_enc=pd.concat([x_test,pe_test_enc,ph_test_enc,li_test_enc], axis=1)

In [34]:
pe_enc.get_feature_names_out()

array(['person_education_Associate', 'person_education_Bachelor',
       'person_education_Doctorate', 'person_education_High School',
       'person_education_Master'], dtype=object)

In [35]:
ph_enc.get_feature_names_out()

array(['person_home_ownership_MORTGAGE', 'person_home_ownership_OTHER',
       'person_home_ownership_OWN', 'person_home_ownership_RENT'],
      dtype=object)

In [36]:
li_enc.get_feature_names_out()

array(['loan_intent_DEBTCONSOLIDATION', 'loan_intent_EDUCATION',
       'loan_intent_HOMEIMPROVEMENT', 'loan_intent_MEDICAL',
       'loan_intent_PERSONAL', 'loan_intent_VENTURE'], dtype=object)

In [37]:
fn_pe = 'pe_enc.pkl'
pkl.dump(pe_enc, open(fn_pe, 'wb'))

fn_ph = 'ph_enc.pkl'
pkl.dump(ph_enc, open(fn_ph, 'wb'))

fn_li = 'li_enc.pkl'
pkl.dump(li_enc, open(fn_li, 'wb'))

In [38]:
x_train_enc.head()

,index,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,...,person_home_ownership_MORTGAGE,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_DEBTCONSOLIDATION,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE
0,25180,34.0,0,Bachelor,97265.0,11,MORTGAGE,15000.0,PERSONAL,12.73,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,12555,25.0,1,High School,0.0,3,RENT,12000.0,VENTURE,11.86,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2,29153,41.0,0,Master,322597.0,18,MORTGAGE,24000.0,PERSONAL,10.37,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,23838,27.0,1,Associate,94232.0,4,RENT,9600.0,EDUCATION,17.14,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,35686,27.0,1,Master,0.0,7,RENT,7059.0,HOMEIMPROVEMENT,12.97,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0

In [39]:
x_test_enc.head()

,index,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,...,person_home_ownership_MORTGAGE,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_DEBTCONSOLIDATION,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE
0,37979,32.0,1,Associate,96865.0,10,MORTGAGE,7500.0,EDUCATION,6.04,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,9911,24.0,1,Associate,56838.0,6,RENT,9000.0,EDUCATION,11.49,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
2,43386,22.0,0,Master,37298.0,0,RENT,5000.0,MEDICAL,14.88,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3,13822,23.0,0,Bachelor,39944.0,1,OWN,5000.0,VENTURE,13.99,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,44810,42.0,1,High School,67974.0,20,MORTGAGE,10000.0,HOMEIMPROVEMENT,15.41,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [40]:
x_train_enc.columns

Index(['index', 'person_age', 'person_gender', 'person_education',
       'person_income', 'person_emp_exp', 'person_home_ownership', 'loan_amnt',
       'loan_intent', 'loan_int_rate', 'loan_percent_income',
       'cb_person_cred_hist_length', 'credit_score',
       'previous_loan_defaults_on_file', 'person_education_Associate',
       'person_education_Bachelor', 'person_education_Doctorate',
       'person_education_High School', 'person_education_Master',
       'person_home_ownership_MORTGAGE', 'person_home_ownership_OTHER',
       'person_home_ownership_OWN', 'person_home_ownership_RENT',
       'loan_intent_DEBTCONSOLIDATION', 'loan_intent_EDUCATION',
       'loan_intent_HOMEIMPROVEMENT', 'loan_intent_MEDICAL',
       'loan_intent_PERSONAL', 'loan_intent_VENTURE'],
      dtype='object')

In [41]:
x_test_enc.columns

Index(['index', 'person_age', 'person_gender', 'person_education',
       'person_income', 'person_emp_exp', 'person_home_ownership', 'loan_amnt',
       'loan_intent', 'loan_int_rate', 'loan_percent_income',
       'cb_person_cred_hist_length', 'credit_score',
       'previous_loan_defaults_on_file', 'person_education_Associate',
       'person_education_Bachelor', 'person_education_Doctorate',
       'person_education_High School', 'person_education_Master',
       'person_home_ownership_MORTGAGE', 'person_home_ownership_OTHER',
       'person_home_ownership_OWN', 'person_home_ownership_RENT',
       'loan_intent_DEBTCONSOLIDATION', 'loan_intent_EDUCATION',
       'loan_intent_HOMEIMPROVEMENT', 'loan_intent_MEDICAL',
       'loan_intent_PERSONAL', 'loan_intent_VENTURE'],
      dtype='object')

Code di bawah error karena sebelumnya level_0 sudah di drop dan tidak ada lagi tetapi codenya di run kembali

In [42]:
#x_train_enc['level_0'].value_counts()

In [43]:
#x_test_enc['level_0'].value_counts()

Melakukan drop pada column yang sudah encoded tadi karena sudah di representasikan melalui one-hot encoder yang tadi kita buat, dan harusnya ada level_0 juga yang di drop tetapi
sebelumnya sudah di drop dan code di jalankan kembali

In [44]:
x_train_enc=x_train_enc.drop(['index','person_education', 'person_home_ownership', 'loan_intent'],axis=1)
x_test_enc=x_test_enc.drop(['index','person_education', 'person_home_ownership', 'loan_intent'],axis=1)

In [45]:
x_train_enc.columns

Index(['person_age', 'person_gender', 'person_income', 'person_emp_exp',
       'loan_amnt', 'loan_int_rate', 'loan_percent_income',
       'cb_person_cred_hist_length', 'credit_score',
       'previous_loan_defaults_on_file', 'person_education_Associate',
       'person_education_Bachelor', 'person_education_Doctorate',
       'person_education_High School', 'person_education_Master',
       'person_home_ownership_MORTGAGE', 'person_home_ownership_OTHER',
       'person_home_ownership_OWN', 'person_home_ownership_RENT',
       'loan_intent_DEBTCONSOLIDATION', 'loan_intent_EDUCATION',
       'loan_intent_HOMEIMPROVEMENT', 'loan_intent_MEDICAL',
       'loan_intent_PERSONAL', 'loan_intent_VENTURE'],
      dtype='object')

In [46]:
x_train_enc.head()

,person_age,person_gender,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,...,person_home_ownership_MORTGAGE,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_DEBTCONSOLIDATION,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE
0,34.0,0,97265.0,11,15000.0,12.73,0.15,9.0,631,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,25.0,1,0.0,3,12000.0,11.86,0.16,4.0,659,1,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2,41.0,0,322597.0,18,24000.0,10.37,0.07,11.0,683,1,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,27.0,1,94232.0,4,9600.0,17.14,0.10,7.0,641,0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,27.0,1,0.0,7,7059.0,12.97,0.08,3.0,706,1,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0

In [47]:
x_test_enc.columns

Index(['person_age', 'person_gender', 'person_income', 'person_emp_exp',
       'loan_amnt', 'loan_int_rate', 'loan_percent_income',
       'cb_person_cred_hist_length', 'credit_score',
       'previous_loan_defaults_on_file', 'person_education_Associate',
       'person_education_Bachelor', 'person_education_Doctorate',
       'person_education_High School', 'person_education_Master',
       'person_home_ownership_MORTGAGE', 'person_home_ownership_OTHER',
       'person_home_ownership_OWN', 'person_home_ownership_RENT',
       'loan_intent_DEBTCONSOLIDATION', 'loan_intent_EDUCATION',
       'loan_intent_HOMEIMPROVEMENT', 'loan_intent_MEDICAL',
       'loan_intent_PERSONAL', 'loan_intent_VENTURE'],
      dtype='object')

In [48]:
x_test_enc.head()

,person_age,person_gender,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,...,person_home_ownership_MORTGAGE,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_DEBTCONSOLIDATION,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE
0,32.0,1,96865.0,10,7500.0,6.04,0.08,10.0,601,0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,24.0,1,56838.0,6,9000.0,11.49,0.16,4.0,647,1,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
2,22.0,0,37298.0,0,5000.0,14.88,0.13,4.0,711,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3,23.0,0,39944.0,1,5000.0,13.99,0.13,3.0,597,1,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,42.0,1,67974.0,20,10000.0,15.41,0.15,11.0,586,0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

Scaling for person_income and loan_amnt

In [49]:
from sklearn.preprocessing import StandardScaler

features_to_scale = ['person_income', 'loan_amnt']

scaler = StandardScaler()

x_train_scaled = x_train_enc.copy()
x_train_scaled[features_to_scale] = scaler.fit_transform(x_train_enc[features_to_scale])

x_test_scaled = x_test_enc.copy()
x_test_scaled[features_to_scale] = scaler.transform(x_test_enc[features_to_scale])

In [50]:
x_train_scaled.head()

,person_age,person_gender,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,...,person_home_ownership_MORTGAGE,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_DEBTCONSOLIDATION,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE
0,34.0,0,0.267292,11,0.859025,12.73,0.15,9.0,631,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,25.0,1,-0.988538,3,0.383393,11.86,0.16,4.0,659,1,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2,41.0,0,3.176648,18,2.285919,10.37,0.07,11.0,683,1,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,27.0,1,0.228131,4,0.002888,17.14,0.10,7.0,641,0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,27.0,1,-0.988538,7,-0.399971,12.97,0.08,3.0,706,1,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0

Modeling using XGBoost Classifier and Random Forest Classifier

In [73]:
from sklearn.ensemble import RandomForestClassifier
import warnings
warnings.filterwarnings('ignore')

rfc = RandomForestClassifier()
rfc.fit(x_train_scaled, y_train)

RandomForestClassifier()

In [74]:
rfcpred = rfc.predict(x_test_scaled)

In [75]:
from sklearn.metrics import classification_report
print(classification_report(y_test, rfcpred, target_names=['Test','Pred']))

              precision    recall  f1-score   support

        Test       0.94      0.97      0.95      6990
        Pred       0.90      0.77      0.83      2010

    accuracy                           0.93      9000
   macro avg       0.92      0.87      0.89      9000
weighted avg       0.93      0.93      0.93      9000

In [76]:
from xgboost import XGBClassifier

xgbc = XGBClassifier()
xgbc.fit(x_train_scaled,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [77]:
xgbpred = xgbc.predict(x_test_scaled)

In [78]:
print(classification_report(y_test, xgbpred,target_names=['Test','Pred']))

              precision    recall  f1-score   support

        Test       0.94      0.97      0.96      6990
        Pred       0.89      0.80      0.84      2010

    accuracy                           0.93      9000
   macro avg       0.92      0.89      0.90      9000
weighted avg       0.93      0.93      0.93      9000

In [79]:
filename = 'XGBCLoan.pkl'
pkl.dump(xgbc, open(filename, 'wb'))